# Session-registry PowerShell module.
#
# Canonical source for the ~80-line session-assignment dance that used to
# live in THREE separate files (statusline.ps1, hooks/speak-response.ps1,
# hooks/speak-on-tool.ps1), each with a "MUST stay in lock-step" comment
# and an ever-present risk of drift. Extracted per audit CC-4.
#
# The JS writer lives at app/main.js (ensureAssignmentsForFiles +
# sanitiseEntry + saveAssignments) and MUST use the identical entry
# schema and assignment algorithm. The shape is:
#
#   { assignments: { <short8>: {
#       index:      int 0..23,           # palette slot
#       session_id: string,              # full Claude Code session uuid
#       claude_pid: int,                 # parent Claude Code PID (0 if unknown)
#       label:      string,              # user-editable, default ''
#       pinned:     bool,                # true = never reassign
#       muted:      bool,                # skip synthesis entirely
#       focus:      bool,                # priority playback (exclusive)
#       last_seen:  long (epoch seconds),
#       voice?:     string,              # optional per-session voice
#       voice_auto?: bool,               # true = assigned by Terminal Talk,
#                                        # false = user chose/cleared manually
#       heartbeat_enabled?: bool,        # optional per-session heartbeat override
#       auto_label?: bool,               # label was generated by Terminal Talk
#       source_kind?: string,            # e.g. codex-plugin
#       source_label?: string,           # human readable generated source label
#       speech_includes?: { <flag>: bool }  # optional per-session overrides
#   } } }
#
# Palette size matches app/renderer.js PALETTE_SIZE (24).

Set-Variable -Scope Script -Name PaletteSize -Value 24 -Option ReadOnly -Force
Set-Variable -Scope Script -Name PaletteAutoOrder -Value @(0,4,3,5,2,6,7,16,11,9,10,14,20,8,12,13,17,18,19,21,22,23,1,15) -Option ReadOnly -Force
Set-Variable -Scope Script -Name AutoEdgeVoiceOrder -Value @(
    'en-AU-NatashaNeural',
    'en-GB-SoniaNeural',
    'en-GB-RyanNeural',
    'en-GB-LibbyNeural',
    'en-GB-ThomasNeural',
    'en-GB-MaisieNeural',
    'en-US-AriaNeural',
    'en-US-JennyNeural',
    'en-US-GuyNeural',
    'en-US-AndrewNeural',
    'en-US-AndrewMultilingualNeural',
    'en-US-EmmaNeural',
    'en-US-EmmaMultilingualNeural',
    'en-US-AvaNeural',
    'en-US-AvaMultilingualNeural',
    'en-US-BrianNeural',
    'en-US-BrianMultilingualNeural',
    'en-US-ChristopherNeural',
    'en-US-EricNeural',
    'en-US-MichelleNeural',
    'en-US-RogerNeural',
    'en-US-SteffanNeural',
    'en-US-AnaNeural',
    'en-AU-WilliamMultilingualNeural',
    'en-CA-ClaraNeural',
    'en-CA-LiamNeural',
    'en-IE-EmilyNeural',
    'en-IE-ConnorNeural',
    'en-IN-NeerjaNeural',
    'en-IN-NeerjaExpressiveNeural',
    'en-IN-PrabhatNeural',
    'en-NZ-MollyNeural',
    'en-NZ-MitchellNeural',
    'en-ZA-LeahNeural',
    'en-ZA-LukeNeural',
    'en-HK-YanNeural',
    'en-HK-SamNeural',
    'en-SG-LunaNeural',
    'en-SG-WayneNeural',
    'en-PH-RosaNeural',
    'en-PH-JamesNeural',
    'en-NG-EzinneNeural',
    'en-NG-AbeoNeural',
    'en-KE-AsiliaNeural',
    'en-KE-ChilembaNeural',
    'en-TZ-ImaniNeural',
    'en-TZ-ElimuNeural'
) -Option ReadOnly -Force

# Lock semantics mirror app/lib/registry-lock.js exactly so JS + PS writers
# serialise against the same .lock file. Without this, the PS statusline /
# speak-* hooks can read a pre-change registry into memory while the JS
# toolbar is mid-write, then `Save-Registry` stomps the toolbar's change.
# Visible symptom: colour / label / mute changes in Settings don't stick.
Set-Variable -Scope Script -Name LockStaleMs       -Value 3000 -Option ReadOnly -Force
Set-Variable -Scope Script -Name LockAcquireMs     -Value 500  -Option ReadOnly -Force
Set-Variable -Scope Script -Name LockPollMs        -Value 15   -Option ReadOnly -Force
Set-Variable -Scope Script -Name RegistryMetaStringFields -Value @(
    'source_kind',
    'source_label',
    'source_app',
    'source_cwd',
    'source',
    'source_originator',
    'source_pid',
    'source_child_pid',
    'source_key',
    'adapter',
    'claude_code_entrypoint',
    'codex_desktop_title_status',
    'codex_desktop_title',
    'codex_desktop_title_error',
    'claude_desktop_title_status',
    'claude_desktop_title',
    'claude_desktop_title_error',
    'claude_desktop_session_file',
    'claude_desktop_renderer_title'
) -Option ReadOnly -Force
Set-Variable -Scope Script -Name RegistryCapabilityFields -Value @(
    'auto_register',
    'tool_events',
    'response_events',
    'mcp_speak',
    'manual_speak_selection'
) -Option ReadOnly -Force

# Window (seconds) during which a non-zero claude_pid on an existing
# entry is considered fresh enough to re-key for /clear migration.
# 600 s covers any realistic gap between consecutive hook fires on
# one terminal; anything older suggests Windows pid reuse, not the
# same live terminal, so we fall through to fresh palette allocation.
Set-Variable -Scope Script -Name PidMigrateWindowSec -Value 600 -Option ReadOnly -Force

function Test-EntryHasKey {
    param($Entry, [string]$Name)
    if (-not $Entry) { return $false }
    if ($Entry -is [hashtable]) { return $Entry.ContainsKey($Name) }
    return $Entry.PSObject.Properties.Name -contains $Name
}

function Get-EntryValue {
    param($Entry, [string]$Name)
    if (-not $Entry) { return $null }
    if ($Entry -is [hashtable]) {
        if ($Entry.ContainsKey($Name)) { return $Entry[$Name] }
        return $null
    }
    if ($Entry.PSObject.Properties.Name -contains $Name) { return $Entry.$Name }
    return $null
}

function Copy-RegistryCapabilities {
    param($Source, [hashtable]$Target)
    if (-not $Source -or -not $Target) { return }
    $caps = Get-EntryValue $Source 'capabilities'
    if (-not $caps) { return }
    $out = @{}
    foreach ($capName in $script:RegistryCapabilityFields) {
        $value = Get-EntryValue $caps $capName
        if ($value -is [bool]) { $out[$capName] = [bool]$value }
    }
    if ($out.Count -gt 0) { $Target['capabilities'] = $out }
}

function Test-ManualVoiceIntent {
    param($Entry)
    if (-not $Entry) { return $false }
    $voice = Get-EntryValue $Entry 'voice'
    $voiceAutoKnown = Test-EntryHasKey $Entry 'voice_auto'
    $voiceAuto = Get-EntryValue $Entry 'voice_auto'
    if ($voice -and -not ($voiceAutoKnown -and $voiceAuto -eq $true)) { return $true }
    if ($voiceAutoKnown -and $voiceAuto -eq $false) { return $true }
    return $false
}

function Test-ShouldAutoAssignVoice {
    param($Entry)
    if (-not $Entry) { return $false }
    $voice = Get-EntryValue $Entry 'voice'
    if ($voice) { return $false }
    $voiceAutoKnown = Test-EntryHasKey $Entry 'voice_auto'
    $voiceAuto = Get-EntryValue $Entry 'voice_auto'
    return -not ($voiceAutoKnown -and $voiceAuto -eq $false)
}

function Get-AutoSessionVoice {
    param([hashtable]$Assignments)
    $counts = @{}
    foreach ($voice in $script:AutoEdgeVoiceOrder) { $counts[$voice] = 0 }
    foreach ($key in @($Assignments.Keys)) {
        $voice = Get-EntryValue $Assignments[$key] 'voice'
        if ($voice -and $counts.ContainsKey([string]$voice)) {
            $counts[[string]$voice] = [int]$counts[[string]$voice] + 1
        }
    }
    foreach ($voice in $script:AutoEdgeVoiceOrder) {
        if ([int]$counts[$voice] -eq 0) { return $voice }
    }
    $best = [string]$script:AutoEdgeVoiceOrder[0]
    $bestCount = [int]$counts[$best]
    foreach ($voice in $script:AutoEdgeVoiceOrder) {
        $count = [int]$counts[$voice]
        if ($count -lt $bestCount) {
            $best = [string]$voice
            $bestCount = $count
        }
    }
    return $best
}

function Set-AutoSessionVoice {
    param([hashtable]$Entry, [hashtable]$Assignments)
    if (-not (Test-ShouldAutoAssignVoice $Entry)) { return '' }
    $voice = Get-AutoSessionVoice -Assignments $Assignments
    if (-not $voice) { return '' }
    $Entry['voice'] = [string]$voice
    $Entry['voice_auto'] = $true
    return [string]$voice
}

function Get-PaletteAutoOrder {
    param([int]$Size)
    $seen = @{}
    $out = @()
    foreach ($idx in $script:PaletteAutoOrder) {
        if ($idx -ge 0 -and $idx -lt $Size -and -not $seen.ContainsKey($idx)) {
            $out += [int]$idx
            $seen[[int]$idx] = $true
        }
    }
    for ($i = 0; $i -lt $Size; $i++) {
        if (-not $seen.ContainsKey($i)) { $out += [int]$i }
    }
    return $out
}

function Enter-RegistryLock {
    <#
    .SYNOPSIS
    Atomic-create a `<RegistryPath>.lock` file using CreateNew + no sharing
    (O_EXCL equivalent). Returns $true on acquisition, $false if the lock
    is held by another process and couldn't be claimed within the timeout.

    A lock file older than $script:LockStaleMs is considered abandoned
    (crashed holder that never released) and stolen. If the acquire loop
    times out we return $false; callers fall through unlocked rather than
    freezing the statusline. This matches the JS wrapper in
    app/lib/registry-lock.js line-for-line.
    #>
    param([Parameter(Mandatory = $true)] [string]$RegistryPath)
    $lockPath = "$RegistryPath.lock"
    $start = [Environment]::TickCount64
    while (([Environment]::TickCount64 - $start) -lt $script:LockAcquireMs) {
        try {
            $fs = [IO.File]::Open($lockPath, [IO.FileMode]::CreateNew, [IO.FileAccess]::Write, [IO.FileShare]::None)
            try {
                $bytes = [Text.Encoding]::UTF8.GetBytes([string]$PID)
                $fs.Write($bytes, 0, $bytes.Length)
            } finally {
                $fs.Close()
            }
            return $true
        } catch [IO.IOException] {
            try {
                $st = Get-Item $lockPath -Force -ErrorAction Stop
                $ageMs = ([DateTime]::UtcNow - $st.LastWriteTimeUtc).TotalMilliseconds
                if ($ageMs -gt $script:LockStaleMs) {
                    Remove-Item $lockPath -Force -ErrorAction SilentlyContinue
                    continue
                }
            } catch {
                # Stat may race with the other holder releasing -- fall through
                # and retry rather than spin-panicking.
            }
            Start-Sleep -Milliseconds $script:LockPollMs
        }
    }
    return $false
}

function Exit-RegistryLock {
    <#
    .SYNOPSIS
    Delete the `<RegistryPath>.lock` sentinel. Idempotent -- a missing file
    is a no-op (acquire may have timed out and we're releasing a lock we
    never held). Never throws.
    #>
    param([Parameter(Mandatory = $true)] [string]$RegistryPath)
    $lockPath = "$RegistryPath.lock"
    Remove-Item $lockPath -Force -ErrorAction SilentlyContinue
}

function Read-Registry {
    <#
    .SYNOPSIS
    Read the session registry from disk and return a normalised hashtable
    of { short8 -> entry-hashtable }. Returns an empty hashtable if the
    file doesn't exist or is malformed -- never throws.
    #>
    param(
        [Parameter(Mandatory = $true)]
        [string]$RegistryPath
    )

    $assignments = @{}
    if (-not (Test-Path $RegistryPath)) { return $assignments }

    try {
        $raw = Get-Content $RegistryPath -Raw -Encoding utf8
        if (-not $raw) { return $assignments }
        $parsed = $raw | ConvertFrom-Json
        if (-not $parsed.assignments) { return $assignments }

        foreach ($p in $parsed.assignments.PSObject.Properties) {
            $v = $p.Value
            $entry = @{
                index      = [int]$v.index
                session_id = [string]$v.session_id
                claude_pid = if ($v.claude_pid) { [int]$v.claude_pid } else { 0 }
                label      = if ($v.label) { [string]$v.label } else { '' }
                pinned     = if ($v.pinned) { [bool]$v.pinned } else { $false }
                muted      = ($v.PSObject.Properties.Name -contains 'muted') -and ($v.muted -eq $true)
                focus      = ($v.PSObject.Properties.Name -contains 'focus') -and ($v.focus -eq $true)
                last_seen  = [long]$v.last_seen
            }
            # Preserve per-session voice / heartbeat / speech_includes
            # overrides through every read/write cycle -- the Electron UI
            # writes these too.
            if ($v.PSObject.Properties.Name -contains 'voice' -and $v.voice) {
                $entry['voice'] = [string]$v.voice
            }
            if ($v.PSObject.Properties.Name -contains 'voice_auto' -and ($v.voice_auto -is [bool])) {
                $entry['voice_auto'] = [bool]$v.voice_auto
            } elseif ($entry.ContainsKey('voice')) {
                $entry['voice_auto'] = $false
            }
            if ($v.PSObject.Properties.Name -contains 'heartbeat_enabled' -and ($v.heartbeat_enabled -is [bool])) {
                $entry['heartbeat_enabled'] = [bool]$v.heartbeat_enabled
            }
            if ($v.PSObject.Properties.Name -contains 'auto_label' -and ($v.auto_label -is [bool])) {
                $entry['auto_label'] = [bool]$v.auto_label
            }
            foreach ($metaName in $script:RegistryMetaStringFields) {
                if ($v.PSObject.Properties.Name -contains $metaName -and $v.$metaName) {
                    $entry[$metaName] = [string]$v.$metaName
                }
            }
            if ($v.PSObject.Properties.Name -contains 'codex_desktop_title_synced_at' -and $v.codex_desktop_title_synced_at) {
                $entry['codex_desktop_title_synced_at'] = [long]$v.codex_desktop_title_synced_at
            }
            if ($v.PSObject.Properties.Name -contains 'claude_desktop_title_synced_at' -and $v.claude_desktop_title_synced_at) {
                $entry['claude_desktop_title_synced_at'] = [long]$v.claude_desktop_title_synced_at
            }
            if ($v.PSObject.Properties.Name -contains 'speech_includes' -and $v.speech_includes) {
                $inc = @{}
                foreach ($ip in $v.speech_includes.PSObject.Properties) {
                    if ($ip.Value -is [bool]) { $inc[$ip.Name] = [bool]$ip.Value }
                }
                $entry['speech_includes'] = $inc
            }
            Copy-RegistryCapabilities -Source $v -Target $entry
            $assignments[$p.Name] = $entry
        }
    } catch {
        # Corrupt registry file: treat as empty. main.js has the same
        # tolerance. The next write will overwrite it with clean JSON.
    }
    return $assignments
}

function Set-ClaudeDesktopMetadata {
    param(
        [hashtable]$Entry,
        [int]$ClaudePid,
        [string]$SessionId
    )
    if (-not $Entry -or $ClaudePid -le 0) { return $false }

    $parentProc = $null
    try {
        $parentProc = Get-CimInstance Win32_Process -Filter "ProcessId=$ClaudePid" -ErrorAction Stop |
            Select-Object -First 1
    } catch {}

    $isDesktopParent = $false
    if ($parentProc) {
        $exe = [string]$parentProc.ExecutablePath
        if ($exe -match '\\WindowsApps\\Claude_.*\\app\\claude\.exe$') {
            $isDesktopParent = $true
        }
    }

    $sessionMeta = $null
    $childPid = 0
    if ($SessionId) {
        try {
            $children = @(Get-CimInstance Win32_Process -ErrorAction Stop |
                Where-Object {
                    [int]$_.ParentProcessId -eq $ClaudePid -and
                    [string]$_.Name -eq 'claude.exe'
                })
            foreach ($child in $children) {
                $candidate = Join-Path $env:USERPROFILE ".claude\sessions\$($child.ProcessId).json"
                if (-not (Test-Path $candidate)) { continue }
                try {
                    $parsed = Get-Content $candidate -Raw -Encoding utf8 | ConvertFrom-Json
                    if ([string]$parsed.sessionId -eq $SessionId) {
                        $sessionMeta = $parsed
                        $childPid = [int]$child.ProcessId
                        break
                    }
                } catch {}
            }
        } catch {}
    }

    $entrypoint = ''
    if ($sessionMeta -and $sessionMeta.entrypoint) { $entrypoint = [string]$sessionMeta.entrypoint }
    $isDesktopSession = $isDesktopParent -or $entrypoint -eq 'claude-desktop'
    if (-not $isDesktopSession) { return $false }

    $Entry['source_kind'] = 'claude-desktop'
    $Entry['source_label'] = 'Claude Desktop'
    $Entry['source_app'] = 'Claude'
    $Entry['source_pid'] = [string]$ClaudePid
    if ($SessionId) { $Entry['source_key'] = "claude-desktop:$SessionId" }
    $Entry['adapter'] = 'hooks'
    $Entry['claude_code_entrypoint'] = if ($entrypoint) { $entrypoint } else { 'claude-desktop' }
    if ($childPid -gt 0) { $Entry['source_child_pid'] = [string]$childPid }
    if ($sessionMeta -and $sessionMeta.cwd) { $Entry['source_cwd'] = [string]$sessionMeta.cwd }
    $Entry['pinned'] = $true
    $Entry['capabilities'] = @{
        auto_register = $true
        tool_events = $true
        response_events = $true
        mcp_speak = $false
        manual_speak_selection = $true
    }
    if (-not $Entry.label -or ([string]$Entry.label).Trim().Length -eq 0 -or ($Entry.ContainsKey('auto_label') -and $Entry.auto_label -eq $true)) {
        $Entry.label = 'Claude Desktop'
        $Entry['auto_label'] = $true
    }
    return $true
}

function Update-SessionAssignment {
    <#
    .SYNOPSIS
    Ensure `$Short` has a slot in `$Assignments`. If it already exists,
    touch the bookkeeping (last_seen / session_id / claude_pid). If not,
    pick the first free index from the spread-first palette order and create the entry with
    default fields. Returns the resolved index.

    This function never prunes. Slot freeing is done by main.js's
    ensureAssignmentsForFiles, which applies the following rules via
    isSessionLive():
      - pinned=true sessions are NEVER pruned (user opt-in retention)
      - PID still alive -> keep
      - last_seen within SESSION_GRACE_SEC (14400s = 4h) -> keep
      - otherwise -> remove

    The settings panel's x button is the user-driven path to the same
    outcome. Call sites here just touch bookkeeping; they rely on
    main.js being authoritative for lifetime decisions.
    #>
    param(
        [Parameter(Mandatory = $true)] [hashtable]$Assignments,
        [Parameter(Mandatory = $true)] [string]$Short,
        [Parameter(Mandatory = $true)] [string]$SessionId,
        [Parameter(Mandatory = $true)] [int]$ClaudePid,
        [Parameter(Mandatory = $true)] [long]$Now,
        # #6 G4 — when -LogPath + -Caller are provided, emit one
        # `update-session <short> -> <branch> index=<idx> pid=<pid>`
        # line per call so PID-migration / fresh-alloc / lru-evict
        # paths are diagnosable from logs alone. Branches:
        #   existing-hit  — short already in registry, bookkeeping only
        #   pid-migration — re-keyed from old short via PID match
        #   fresh-alloc   — spread-first free palette slot taken
        #   lru-evict     — evicted a no-intent entry to free a slot
        #   hash-collision — palette full of intent-bearing entries
        # Optional so existing test call sites + un-instrumented
        # callers stay back-compat.
        [string]$LogPath = '',
        [string]$Caller = 'unknown'
    )

    # PSScriptAnalyzer can't follow $LogPath/$Caller usage into the
    # nested function _LogBranch. Touch them once at the top of the
    # parent body so the analyzer sees the params consumed and the
    # PSReviewUnusedParameter rule passes. The Out-Null cast is a
    # zero-side-effect read that compiles to a single instruction.
    $null = $LogPath; $null = $Caller

    function _LogBranch($branch, $idx) {
        if (-not $LogPath) { return }
        $ts = (Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
        $line = "$ts update-session $Short -> $branch index=$idx pid=$ClaudePid from=$Caller"
        try { Add-Content -Path $LogPath -Value $line -ErrorAction SilentlyContinue } catch {}
    }

    if ($Assignments.ContainsKey($Short)) {
        $Assignments[$Short].last_seen  = $Now
        $Assignments[$Short].session_id = $SessionId
        $Assignments[$Short].claude_pid = $ClaudePid
        [void](Set-ClaudeDesktopMetadata -Entry $Assignments[$Short] -ClaudePid $ClaudePid -SessionId $SessionId)
        [void](Set-AutoSessionVoice -Entry $Assignments[$Short] -Assignments $Assignments)
        $idx0 = [int]$Assignments[$Short].index
        _LogBranch 'existing-hit' $idx0
        return $idx0
    }

    # PID-identity migration. Claude Code's /clear rotates session_id but
    # keeps the same CLI process, so the same terminal walks in here with
    # a brand-new short. Without this migration we allocate a fresh
    # palette slot -- the user sees their colour "change" and their label
    # vanish, even though the terminal is the same. If an existing entry
    # has this claude_pid we re-key it under the new short, preserving
    # index / label / pinned / muted / focus / voice / heartbeat /
    # speech_includes.
    #
    # Guards against false migration:
    #   1. Only match on non-zero pids: 0 means "unknown" and would
    #      collide across ghost entries created by main.js's queue-
    #      scanner fallback.
    #   2. Require freshness -- the matched entry's last_seen must be
    #      within $PidMigrateWindowSec. Without this, Windows reusing a
    #      pid hours later (rare but possible) would let a brand-new
    #      terminal inherit a long-dead session's colour and label.
    if ($ClaudePid -gt 0) {
        $cutoff = $Now - $script:PidMigrateWindowSec
        $oldShort = $null
        foreach ($key in @($Assignments.Keys)) {
            $entry = $Assignments[$key]
            if ([int]$entry.claude_pid -eq $ClaudePid -and [long]$entry.last_seen -ge $cutoff) {
                $oldShort = $key
                break
            }
        }
        if ($oldShort) {
            $migrated = $Assignments[$oldShort]
            $migrated.session_id = $SessionId
            $migrated.claude_pid = $ClaudePid
            $migrated.last_seen  = $Now
            [void](Set-ClaudeDesktopMetadata -Entry $migrated -ClaudePid $ClaudePid -SessionId $SessionId)
            $Assignments[$Short] = $migrated
            [void]$Assignments.Remove($oldShort)
            [void](Set-AutoSessionVoice -Entry $migrated -Assignments $Assignments)
            $idxM = [int]$migrated.index
            _LogBranch "pid-migration<-$oldShort" $idxM
            return $idxM
        }
    }

    $busy = @{}
    foreach ($key in @($Assignments.Keys)) {
        $busy[[int]$Assignments[$key].index] = $true
    }

    $idx = $null
    foreach ($i in (Get-PaletteAutoOrder -Size $script:PaletteSize)) {
        if (-not $busy.ContainsKey($i)) { $idx = $i; break }
    }

    # Palette full -- LRU eviction among entries with no user intent.
    # An entry is protected from eviction if pinned OR if it carries
    # any user customisation (label / voice / heartbeat / muted /
    # focus / speech_includes). Matches allocatePaletteIndex() + hasUserIntent()
    # in app/lib/palette-alloc.js so statusline + Electron UI always
    # agree on the candidate pool.
    $branchTag = 'fresh-alloc'
    if ($null -eq $idx) {
        $candidates = @()
        foreach ($key in @($Assignments.Keys)) {
            $entry = $Assignments[$key]
            $hasIntent = $false
            if ($entry.pinned -eq $true) { $hasIntent = $true }
            elseif ($entry.label -and ([string]$entry.label).Trim().Length -gt 0 -and -not ($entry.ContainsKey('auto_label') -and $entry.auto_label -eq $true)) { $hasIntent = $true }
            elseif (Test-ManualVoiceIntent $entry) { $hasIntent = $true }
            elseif ($entry.ContainsKey('heartbeat_enabled') -and ($entry.heartbeat_enabled -is [bool])) { $hasIntent = $true }
            elseif ($entry.muted -eq $true) { $hasIntent = $true }
            elseif ($entry.focus -eq $true) { $hasIntent = $true }
            elseif ($entry.speech_includes -and $entry.speech_includes.Count -gt 0) { $hasIntent = $true }
            if (-not $hasIntent) {
                $candidates += [pscustomobject]@{
                    Short = $key
                    LastSeen = [long]([int]$entry.last_seen)
                    Index = [int]$entry.index
                }
            }
        }
        if ($candidates.Count -gt 0) {
            $lru = $candidates | Sort-Object LastSeen, Short | Select-Object -First 1
            $idx = $lru.Index
            [void]$Assignments.Remove($lru.Short)
            $branchTag = "lru-evict<-$($lru.Short)"
        } else {
            # Every slot is pinned -- hash-mod collision is unavoidable.
            $sum = 0
            foreach ($ch in $Short.ToCharArray()) { $sum += [int]$ch }
            $idx = $sum % $script:PaletteSize
            $branchTag = 'hash-collision'
        }
    }

    $newEntry = @{
        index      = [int]$idx
        session_id = $SessionId
        claude_pid = $ClaudePid
        label      = ''
        pinned     = $false
        muted      = $false
        focus      = $false
        last_seen  = $Now
    }
    [void](Set-ClaudeDesktopMetadata -Entry $newEntry -ClaudePid $ClaudePid -SessionId $SessionId)
    [void](Set-AutoSessionVoice -Entry $newEntry -Assignments $Assignments)
    $Assignments[$Short] = $newEntry
    _LogBranch $branchTag ([int]$idx)
    return [int]$idx
}

function Save-Registry {
    <#
    .SYNOPSIS
    Atomic registry write: serialise to `.tmp`, then rename over the real
    path. UTF-8 NO-BOM so JSON.parse() in app/main.js accepts the file.
    Silent on failure (registry write is best-effort; next invocation
    will retry from whatever persisted).

    #6 G1 + G3 — when -LogPath is provided, appends one success/failure
    line per write so the JS-side and PS-side writers share the same
    attribution format. `Caller` identifies which hook/statusline
    invoked the save (required for diagnosing #8 wipes — five different
    writers touch session-colours.json).
    #>
    param(
        [Parameter(Mandatory = $true)] [string]$RegistryPath,
        [Parameter(Mandatory = $true)] [hashtable]$Assignments,
        [string]$Caller = 'unknown',
        [string]$LogPath = '',
        [string[]]$SkipRestoreShorts = @()
    )
    $keys = 0
    try { $keys = $Assignments.Keys.Count } catch { $keys = 0 }
    # #8 defensive guard — PS callers (statusline, speak-on-tool,
    # speak-response) are all touch-paths that bump last_seen /
    # claude_pid / session_id but must never wipe user-intent fields.
    # Two restoration modes:
    #   1. MISSING ENTRY — disk has an entry with user-intent that's
    #      absent from the payload. Belt-and-braces catch for the
    #      lock-fail-race where a stale Read-Registry returned an empty
    #      hashtable; Save-Registry would otherwise persist only the
    #      firing terminal's own session, dropping the others.
    #   2. MISSING FIELD — entry exists in both, but payload has fewer
    #      user-intent fields (label / pinned / voice / heartbeat /
    #      muted / focus / speech_includes). Restore the disk value.
    # Mirrors the JS-side _guardUserIntent in main.js.
    $restored = @()
    if (Test-Path $RegistryPath) {
        try {
            $skipRestore = @{}
            foreach ($s in @($SkipRestoreShorts)) {
                $key = ([string]$s).Trim().ToLowerInvariant()
                if ($key -match '^[a-f0-9]{8}$') { $skipRestore[$key] = $true }
            }
            $raw = Get-Content $RegistryPath -Raw -Encoding utf8
            if ($raw) {
                $parsed = $raw | ConvertFrom-Json
                if ($parsed.assignments) {
                    # PID-migration exclusion. Update-SessionAssignment re-keys
                    # entries on /clear; payload's new short inherits old's pid.
                    # Don't restore old short if its pid lives at a different
                    # key in the payload — that's migration, not a wipe.
                    $payloadPids = @{}
                    foreach ($pkey in @($Assignments.Keys)) {
                        $pent = $Assignments[$pkey]
                        if ($pent -and $pent.claude_pid -and [int]$pent.claude_pid -gt 0) {
                            $payloadPids[[int]$pent.claude_pid] = $pkey
                        }
                    }
                    # Missing-entry restoration.
                    foreach ($p in $parsed.assignments.PSObject.Properties) {
                        $short = $p.Name
                        if ($skipRestore.ContainsKey($short)) { continue }
                        if ($Assignments.ContainsKey($short)) { continue }
                        $old = $p.Value
                        $hasIntent = $false
                        $labelIsAuto = ($old.PSObject.Properties.Name -contains 'auto_label' -and $old.auto_label -eq $true)
                        if ($old.pinned -eq $true) { $hasIntent = $true }
                        elseif ($old.label -and ([string]$old.label).Length -gt 0 -and -not $labelIsAuto) { $hasIntent = $true }
                        elseif (Test-ManualVoiceIntent $old) { $hasIntent = $true }
                        elseif ($old.PSObject.Properties.Name -contains 'heartbeat_enabled' -and ($old.heartbeat_enabled -is [bool])) { $hasIntent = $true }
                        elseif ($old.muted -eq $true) { $hasIntent = $true }
                        elseif ($old.focus -eq $true) { $hasIntent = $true }
                        elseif ($old.PSObject.Properties.Name -contains 'speech_includes' -and $old.speech_includes) { $hasIntent = $true }
                        if (-not $hasIntent) { continue }
                        # Skip if pid lives at a different short in the payload.
                        if ($old.claude_pid -and [int]$old.claude_pid -gt 0 -and $payloadPids.ContainsKey([int]$old.claude_pid)) {
                            continue
                        }
                        $rebuilt = @{
                            index      = [int]$old.index
                            session_id = [string]$old.session_id
                            claude_pid = if ($old.claude_pid) { [int]$old.claude_pid } else { 0 }
                            label      = if ($old.label) { [string]$old.label } else { '' }
                            pinned     = if ($old.pinned) { [bool]$old.pinned } else { $false }
                            muted      = ($old.PSObject.Properties.Name -contains 'muted') -and ($old.muted -eq $true)
                            focus      = ($old.PSObject.Properties.Name -contains 'focus') -and ($old.focus -eq $true)
                            last_seen  = [long]$old.last_seen
                        }
                        if ($old.PSObject.Properties.Name -contains 'voice' -and $old.voice) {
                            $rebuilt['voice'] = [string]$old.voice
                        }
                        if ($old.PSObject.Properties.Name -contains 'voice_auto' -and ($old.voice_auto -is [bool])) {
                            $rebuilt['voice_auto'] = [bool]$old.voice_auto
                        }
                        if ($old.PSObject.Properties.Name -contains 'heartbeat_enabled' -and ($old.heartbeat_enabled -is [bool])) {
                            $rebuilt['heartbeat_enabled'] = [bool]$old.heartbeat_enabled
                        }
                        if ($old.PSObject.Properties.Name -contains 'auto_label' -and ($old.auto_label -is [bool])) {
                            $rebuilt['auto_label'] = [bool]$old.auto_label
                        }
                        foreach ($metaName in $script:RegistryMetaStringFields) {
                            if ($old.PSObject.Properties.Name -contains $metaName -and $old.$metaName) {
                                $rebuilt[$metaName] = [string]$old.$metaName
                            }
                        }
                        if ($old.PSObject.Properties.Name -contains 'codex_desktop_title_synced_at' -and $old.codex_desktop_title_synced_at) {
                            $rebuilt['codex_desktop_title_synced_at'] = [long]$old.codex_desktop_title_synced_at
                        }
                        if ($old.PSObject.Properties.Name -contains 'claude_desktop_title_synced_at' -and $old.claude_desktop_title_synced_at) {
                            $rebuilt['claude_desktop_title_synced_at'] = [long]$old.claude_desktop_title_synced_at
                        }
                        if ($old.PSObject.Properties.Name -contains 'speech_includes' -and $old.speech_includes) {
                            $inc = @{}
                            foreach ($ip in $old.speech_includes.PSObject.Properties) {
                                if ($ip.Value -is [bool]) { $inc[$ip.Name] = [bool]$ip.Value }
                            }
                            if ($inc.Count -gt 0) { $rebuilt['speech_includes'] = $inc }
                        }
                        Copy-RegistryCapabilities -Source $old -Target $rebuilt
                        $Assignments[$short] = $rebuilt
                        $restored += "${short}:*missing*"
                    }
                    # Per-field restoration on entries now present in both
                    # (either originally or via missing-entry restoration above).
                    foreach ($p in $parsed.assignments.PSObject.Properties) {
                        $short = $p.Name
                        if (-not $Assignments.ContainsKey($short)) { continue }
                        $old = $p.Value
                        $new = $Assignments[$short]
                        if (-not $new) { continue }
                        if ($old.label -and ([string]$old.label).Length -gt 0 -and -not ($old.PSObject.Properties.Name -contains 'auto_label' -and $old.auto_label -eq $true) -and (-not $new.label -or ([string]$new.label).Length -eq 0)) {
                            $new.label = [string]$old.label
                            $restored += "${short}:label"
                        }
                        if ($old.pinned -eq $true -and $new.pinned -ne $true) {
                            $new.pinned = $true
                            $restored += "${short}:pinned"
                        }
                        # Index restoration. Touch-path writers (statusline,
                        # speak-on-tool, speak-response, codex-session-watcher)
                        # load + touch + write. If the user changed the palette
                        # index between load and write, the stale payload would
                        # clobber the user's choice. Restore when the entry has
                        # user-intent and the indices differ. set-session-index
                        # short-circuits via the JS guard before this PS path
                        # is reached, so its writes stay intact.
                        $oldHasIntent = $false
                        $oldLabelAuto = ($old.PSObject.Properties.Name -contains 'auto_label' -and $old.auto_label -eq $true)
                        if ($old.pinned -eq $true) { $oldHasIntent = $true }
                        elseif ($old.label -and ([string]$old.label).Length -gt 0 -and -not $oldLabelAuto) { $oldHasIntent = $true }
                        elseif (Test-ManualVoiceIntent $old) { $oldHasIntent = $true }
                        elseif ($old.muted -eq $true) { $oldHasIntent = $true }
                        elseif ($old.focus -eq $true) { $oldHasIntent = $true }
                        if ($oldHasIntent -and $old.PSObject.Properties.Name -contains 'index' -and
                            ($null -ne $old.index) -and ([int]$old.index -ne [int]$new.index)) {
                            $new.index = [int]$old.index
                            $restored += "${short}:index"
                        }
                        if ($old.PSObject.Properties.Name -contains 'voice_auto' -and ($old.voice_auto -is [bool]) -and $old.voice_auto -eq $false -and
                            (-not ($new.ContainsKey('voice_auto') -and ($new.voice_auto -eq $false)))) {
                            $new['voice_auto'] = $false
                            $restored += "${short}:voice_auto"
                        }
                        if ($old.voice -and -not ($old.PSObject.Properties.Name -contains 'voice_auto' -and $old.voice_auto -eq $true) -and -not $new.voice) {
                            $new.voice = [string]$old.voice
                            $restored += "${short}:voice"
                        }
                        if ($old.PSObject.Properties.Name -contains 'heartbeat_enabled' -and ($old.heartbeat_enabled -is [bool]) -and
                            (-not ($new.ContainsKey('heartbeat_enabled') -and ($new.heartbeat_enabled -is [bool])))) {
                            $new['heartbeat_enabled'] = [bool]$old.heartbeat_enabled
                            $restored += "${short}:heartbeat_enabled"
                        }
                        if ($old.PSObject.Properties.Name -contains 'auto_label' -and ($old.auto_label -is [bool]) -and
                            (-not ($new.ContainsKey('auto_label') -and ($new.auto_label -is [bool])))) {
                            $new['auto_label'] = [bool]$old.auto_label
                            $restored += "${short}:auto_label"
                        }
                        foreach ($metaName in $script:RegistryMetaStringFields) {
                            if ($old.PSObject.Properties.Name -contains $metaName -and $old.$metaName -and
                                (-not ($new.ContainsKey($metaName) -and $new[$metaName]))) {
                                $new[$metaName] = [string]$old.$metaName
                                $restored += "${short}:$metaName"
                            }
                        }
                        if ($old.PSObject.Properties.Name -contains 'codex_desktop_title_synced_at' -and $old.codex_desktop_title_synced_at -and
                            (-not ($new.ContainsKey('codex_desktop_title_synced_at') -and $new['codex_desktop_title_synced_at']))) {
                            $new['codex_desktop_title_synced_at'] = [long]$old.codex_desktop_title_synced_at
                            $restored += "${short}:codex_desktop_title_synced_at"
                        }
                        if ($old.PSObject.Properties.Name -contains 'claude_desktop_title_synced_at' -and $old.claude_desktop_title_synced_at -and
                            (-not ($new.ContainsKey('claude_desktop_title_synced_at') -and $new['claude_desktop_title_synced_at']))) {
                            $new['claude_desktop_title_synced_at'] = [long]$old.claude_desktop_title_synced_at
                            $restored += "${short}:claude_desktop_title_synced_at"
                        }
                        if ($old.muted -eq $true -and $new.muted -ne $true) {
                            $new.muted = $true
                            $restored += "${short}:muted"
                        }
                        if ($old.focus -eq $true -and $new.focus -ne $true) {
                            $new.focus = $true
                            $restored += "${short}:focus"
                        }
                        if ($old.PSObject.Properties.Name -contains 'speech_includes' -and $old.speech_includes -and (-not $new.speech_includes -or $new.speech_includes.Count -eq 0)) {
                            $inc = @{}
                            foreach ($ip in $old.speech_includes.PSObject.Properties) {
                                if ($ip.Value -is [bool]) { $inc[$ip.Name] = [bool]$ip.Value }
                            }
                            if ($inc.Count -gt 0) {
                                $new['speech_includes'] = $inc
                                $restored += "${short}:speech_includes"
                            }
                        }
                        $oldCaps = Get-EntryValue $old 'capabilities'
                        if ($oldCaps) {
                            if (-not ($new.ContainsKey('capabilities') -and $new['capabilities'])) {
                                $new['capabilities'] = @{}
                            }
                            foreach ($capName in $script:RegistryCapabilityFields) {
                                $oldCapValue = Get-EntryValue $oldCaps $capName
                                $newCapValue = Get-EntryValue $new['capabilities'] $capName
                                if (($oldCapValue -is [bool]) -and -not ($newCapValue -is [bool])) {
                                    $new['capabilities'][$capName] = [bool]$oldCapValue
                                    $restored += "${short}:capabilities.$capName"
                                }
                            }
                        }
                    }
                }
            }
        } catch {
            # Best-effort — corrupt/locked file falls through to write.
        }
    }
    try {
        $tmp = "$RegistryPath.tmp"
        $jsonOut = (@{ assignments = $Assignments } | ConvertTo-Json -Depth 5)
        [IO.File]::WriteAllText($tmp, $jsonOut, [System.Text.UTF8Encoding]::new($false))
        Move-Item -Force $tmp $RegistryPath
        if ($LogPath) {
            $ts = (Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
            if ($restored.Count -gt 0) {
                $restoredList = $restored -join ','
                $guardLine = "$ts save-registry GUARD from=$Caller restored=[$restoredList]"
                try { Add-Content -Path $LogPath -Value $guardLine -ErrorAction SilentlyContinue } catch {}
            }
            $line = "$ts save-registry ok from=$Caller keys=$keys"
            try { Add-Content -Path $LogPath -Value $line -ErrorAction SilentlyContinue } catch {}
        }
    } catch {
        if ($LogPath) {
            $ts = (Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
            $err = $_.Exception.Message -replace "[\r\n]+"," "
            $line = "$ts save-registry fail from=$Caller err=$err"
            try { Add-Content -Path $LogPath -Value $line -ErrorAction SilentlyContinue } catch {}
        }
    }
}

function Write-SessionPidFile {
    <#
    .SYNOPSIS
    Stamp a per-PID session file at `$SessionsDir/$Pid.json` so the
    "hey jarvis" / Ctrl+Shift+S flow can map foreground-window PID back
    to its session's colour/short. No-op if pid is 0 (unknown).
    #>
    param(
        [Parameter(Mandatory = $true)] [string]$SessionsDir,
        [Parameter(Mandatory = $true)] [int]$ClaudePid,
        [Parameter(Mandatory = $true)] [string]$SessionId,
        [Parameter(Mandatory = $true)] [string]$Short,
        [Parameter(Mandatory = $true)] [long]$Now
    )
    if (-not $ClaudePid) { return }
    try {
        $sessionFile = Join-Path $SessionsDir "$ClaudePid.json"
        $jsonOut = @{
            session_id = $SessionId
            short      = $Short
            claude_pid = $ClaudePid
            ts         = $Now
        } | ConvertTo-Json -Compress
        $tmp = "$sessionFile.tmp"
        [IO.File]::WriteAllText($tmp, $jsonOut, [System.Text.UTF8Encoding]::new($false))
        Move-Item -Force $tmp $sessionFile
    } catch {
        # Best-effort.
    }
}

function Get-StableClaudePid {
    <#
    .SYNOPSIS
    Walk the parent-process chain from $StartPid and return the OUTERMOST
    `claude.exe` (or `node.exe`) ancestor — the long-lived Claude Code CLI
    process whose pid survives `/clear`.

    Why: hooks used to call
        (Get-CimInstance Win32_Process -Filter "ProcessId=$PID").ParentProcessId
    and store that as `claude_pid`. Empirically, statusLine + PostToolUse
    hooks are invoked through a worker `claude.exe` that the CLI rotates
    per call, so `ParentProcessId` is an EPHEMERAL pid — different on every
    invocation, never matches across `/clear`, and breaks PID-migration
    inside Update-SessionAssignment. Stop hooks (speak-response) happen to
    reach claude.exe directly so their `ParentProcessId` was stable; this
    helper closes the gap by always returning the same outermost
    ancestor regardless of how the hook was invoked.

    Algorithm: walk up to $MaxHops parents. Record every ancestor whose
    Name is `claude.exe` or `node.exe`. Return the LAST (outermost) one
    encountered. If no such ancestor exists, fall back to the original
    1-hop ParentProcessId so behaviour degrades gracefully (matches
    pre-fix output rather than returning 0).

    Parameters:
      -StartPid       PID to walk from (default $PID).
      -MaxHops        Hard ceiling so a loop in OS data can't hang us
                      (default 8 — production trees observed at 2-3).
      -ProcessLookup  Test seam: scriptblock ([int]) -> { Name, ParentProcessId }.
                      Defaults to the live CIM query. Tests pass a
                      hashtable-backed stub so the algorithm runs without
                      touching the real OS process tree.

    Returns: int pid (0 if no parent reachable at all).
    #>
    param(
        [int]$StartPid = $PID,
        [int]$MaxHops = 8,
        [scriptblock]$ProcessLookup = {
            param([int]$LookupPid)
            try {
                Get-CimInstance Win32_Process -Filter "ProcessId=$LookupPid" -ErrorAction Stop |
                    Select-Object -First 1 |
                    Select-Object Name, ProcessId, ParentProcessId
            } catch { $null }
        }
    )
    if ($StartPid -le 0) { return 0 }

    $cur = $StartPid
    $lastClaude = 0
    $oneHopFallback = 0
    for ($hop = 0; $hop -le $MaxHops; $hop++) {
        $proc = & $ProcessLookup $cur
        if (-not $proc) { break }
        if ($hop -eq 1) { $oneHopFallback = $cur }
        if ($hop -ge 1) {
            $name = [string]$proc.Name
            if ($name -eq 'claude.exe' -or $name -eq 'node.exe') {
                $lastClaude = $cur
            }
        }
        $next = [int]$proc.ParentProcessId
        if ($next -le 0 -or $next -eq $cur) { break }
        $cur = $next
    }
    if ($lastClaude -gt 0) { return $lastClaude }
    return $oneHopFallback
}

Export-ModuleMember -Function Read-Registry, Update-SessionAssignment, Save-Registry, Write-SessionPidFile, Enter-RegistryLock, Exit-RegistryLock, Get-StableClaudePid
